"""Engine: decoded packets -> flows, name map, metrics -> detectors -> deduplicated alerts -> sink (Laya triage, outputs).

All detector time is *capture* time (packet timestamps), so a pcap file and a live capture behave identically.
"""
import threading, time
from collections import Counter, defaultdict, deque

from . import decode as D
from .model import Alert
from .netutil import ip_class, is_public, known_service, registrable

REALERT_S = 600          # identical alert keys within this window are folded into one (count++)


class Flow:
    __slots__ = ("proto", "client", "server", "cport", "sport", "first", "last", "pc", "ps", "bc", "bs", "syn", "synack",
                 "rst", "fin", "name", "upload_alerted", "burst_last")

    def __init__(self, proto, client, cport, server, sport, ts):
        self.proto = proto; self.client = client; self.cport = cport; self.server = server; self.sport = sport
        self.first = self.last = ts; self.pc = self.ps = self.bc = self.bs = 0
        self.syn = self.synack = self.rst = self.fin = False; self.name = None; self.upload_alerted = 0
        self.burst_last = 0.0


class Metrics:
    """Wall-clock and capture-clock counters for the dashboard (thread-safe snapshot)."""
    def __init__(self):
        self.lock = threading.Lock()
        self.packets = 0; self.bytes = 0; self.decoded = 0; self.started = time.time()
        self.proto = Counter(); self.app = Counter()
        self.series = deque(maxlen=900)       # (wall_ts, packets_total, pps, bytes_per_s, alerts_total, laya_calls, laya_avg_ms)
        self.cap_first = self.cap_last = None
        self.bytes_out = Counter(); self.bytes_in = Counter()   # per inside host
        self.remote_bytes = Counter()                            # per remote (public) ip
        self.domains = Counter()
        self.flows_active = 0; self.flows_total = 0
        self.duplicates = 0; self.undecoded = Counter()        # linktype -> frames we could not decode
        self.undecoded_samples = deque(maxlen=12)                # hex heads of undecoded frames (diagnostics)
        self.errors = 0; self.log = deque(maxlen=40)             # (wall_ts, message): capture / processing problems
        self.self_excluded = 0                                   # the analyser's own traffic (dashboard, Laya, its PTR lookups)

    def note(self, msg):
        with self.lock:
            self.log.append((time.time(), str(msg)[:300]))


class Engine:
    def __init__(self, sink, local_ips=(), detectors=None, dedupe=False):
        self.sink = sink
        self.local_ips = set(local_ips)
        self.names = {}                                  # ip -> domain (from DNS answers / SNI / HTTP Host)
        self.flows = {}
        self.alerts = {}                                 # key -> Alert (for folding repeats)
        self.m = Metrics()
        self.now = 0.0
        self._next_tick = None
        self.gateway_ips = set()
        self.gw_macs = Counter()                         # dst MAC of public-bound frames -> count
        self.dedupe = dedupe; self._dset = {}
        self._emit_lock = threading.Lock()
        self.own_ptr = set()                             # in-addr.arpa names the review looks up itself
        from .detectors import all_detectors
        self.detectors = detectors if detectors is not None else all_detectors()

    def _own(self, p):
        """Traffic generated by this application: everything on loopback (the dashboard on 127.0.0.1:8765 and the Laya
        server on 127.0.0.1:800x live there) and the reverse-DNS lookups the Laya review makes."""
        if p.src is not None and (p.src.startswith("127.") or p.src == "::1" or p.dst.startswith("127.") or p.dst == "::1"):
            return True
        if p.dns is not None and p.dns.get("qtype") == 12 and p.dns.get("qname") in self.own_ptr:
            return True
        return False

    # ------------------------------------------------------------------ helpers used by detectors
    def is_inside(self, ip):
        return ip in self.local_ips or ip_class(ip) == "private"

    def label(self, ip):
        """'192.168.1.20 (this laptop)' / '142.250.1.1 (www.google.com, Google)' for human + Laya readable stories."""
        if ip is None:
            return "?"
        if ip in self.local_ips or (not self.local_ips and ip == self._top_sender()):
            return f"{ip} (this laptop)"
        if ip in self.gateway_ips:
            return f"{ip} (default gateway)"
        n = self.names.get(ip)
        if n:
            svc = known_service(n)
            return f"{ip} ({n}{', ' + svc if svc else ''})"
        c = ip_class(ip)
        return f"{ip} ({'local network' if c == 'private' else 'internet, no domain name seen' if c == 'public' else c})"

    def _top_sender(self):
        """Without --local, the inside host sending the most to the internet is taken to be the laptop."""
        with self.m.lock:
            top = self.m.bytes_out.most_common(1)
        return top[0][0] if top else None

    def emit(self, ts, detector, category, severity, title, story, src=None, dst=None, key=None, evidence=None,
             laya_mode="triage", laya=None):
        """Raise (or fold into an existing) alert. Thread-safe: the Laya review worker emits too.
        An alert that arrives with a Laya verdict already attached skips triage."""
        key = key or (detector, src, dst, title)
        with self._emit_lock:
            a = self.alerts.get(key)
            if a is not None and ts - a.ts < REALERT_S:
                a.count += 1; a.ts = ts
                self.sink.update(a)
                return a
            a = Alert(ts, detector, category, severity, title, story, src, dst, key, evidence, laya_mode)
            if laya is not None:
                a.laya = laya; a.final = severity
            self.alerts[key] = a
        self.sink.submit(a)
        return a

    # ------------------------------------------------------------------ main entry
    def feed(self, ts, linktype, data, wirelen):
        m = self.m
        with m.lock:
            m.packets += 1
        p = D.decode(ts, linktype, data, wirelen)
        if p is None:
            with m.lock:
                m.undecoded[linktype] += 1; m.bytes += wirelen
                if m.undecoded[linktype] % 500 == 1:
                    m.undecoded_samples.append(f"lt={linktype} len={len(data)} {bytes(data[:64]).hex()}")
            return
        if self._own(p):
            with m.lock:
                m.self_excluded += 1
            return
        if self.dedupe and p.l3key is not None:
            # pktmon logs one packet at several stack layers (802.11 at the NIC, Ethernet above it, filter drivers);
            # the network-layer bytes (IP id, ports, sequence numbers...) identify it across those copies
            seen = self._dset.get(p.l3key)
            if seen is not None and abs(ts - seen) < 1.0:
                with m.lock:
                    m.duplicates += 1
                return
            self._dset[p.l3key] = ts
            if len(self._dset) > 50000:
                self._dset = {k: t for k, t in self._dset.items() if ts - t < 2.0}
        with m.lock:
            m.bytes += p.wirelen
        self.process(p)

    def process(self, p):
        ts = p.ts; m = self.m
        if self._next_tick is None:
            self._next_tick = ts + 1.0
            m.cap_first = ts
        self.now = ts; m.cap_last = ts
        m.decoded += 1
        flow = None
        if p.arp:
            m.proto["ARP"] += 1
        elif p.ipv:
            pname = {D.TCP: "TCP", D.UDP: "UDP", D.ICMP: "ICMP", D.ICMP6: "ICMPv6"}.get(p.proto, f"IP/{p.proto}")
            m.proto[pname] += 1
            if p.dns:
                m.app["DNS"] += 1; self._dns_names(p)
            elif p.tls:
                m.app["TLS"] += 1
            elif p.http:
                m.app["HTTP"] += 1
            elif p.dhcp:
                m.app["DHCP"] += 1
            if p.sport is not None:
                flow = self._flow(p)
            if self.is_inside(p.src) and is_public(p.dst):
                m.bytes_out[p.src] += p.wirelen; m.remote_bytes[p.dst] += p.wirelen
                if p.dst_mac:
                    self.gw_macs[p.dst_mac] += 1
            elif is_public(p.src) and self.is_inside(p.dst):
                m.bytes_in[p.dst] += p.wirelen; m.remote_bytes[p.src] += p.wirelen
        for d in self.detectors:
            d.on_packet(p, flow, self)
        while ts >= self._next_tick:
            self.tick(self._next_tick)
            self._next_tick += 1.0

    def tick(self, now):
        if int(now) % 5 == 0:
            self._expire(now)
        for d in self.detectors:
            d.tick(now, self)

    def finish(self):
        """End of input: let windowed detectors evaluate what they have."""
        if self._next_tick is not None:
            for d in self.detectors:
                d.tick(self.now + 1.0, self, final=True)

    # ------------------------------------------------------------------ flows + names
    def _dns_names(self, p):
        d = p.dns
        if d["qname"] and not d["qr"]:
            with self.m.lock:
                self.m.domains[registrable(d["qname"])] += 1
        if d["qr"] and d["answers"] and d["qname"]:
            for _name, rtype, val in d["answers"]:
                if rtype in (1, 28):
                    self.names[val] = d["qname"]

    def _flow(self, p):
        k = (p.proto, p.src, p.sport, p.dst, p.dport) if (p.src, p.sport) < (p.dst, p.dport) else \
            (p.proto, p.dst, p.dport, p.src, p.sport)
        f = self.flows.get(k)
        if f is None:
            client, cport, server, sport = p.src, p.sport, p.dst, p.dport
            if p.proto == D.TCP and p.flags & D.SYN and p.flags & D.ACK:          # first packet seen is the SYN-ACK
                client, cport, server, sport = p.dst, p.dport, p.src, p.sport
            elif p.proto == D.UDP and p.sport < 1024 <= p.dport:                   # reply from a well-known port
                client, cport, server, sport = p.dst, p.dport, p.src, p.sport
            elif p.proto == D.TCP and not p.flags & D.SYN and p.sport < p.dport and p.sport < 49152:
                client, cport, server, sport = p.dst, p.dport, p.src, p.sport    # joined mid-connection: lower port serves
            f = Flow(p.proto, client, cport, server, sport, p.ts)
            f.name = self.names.get(server)
            self.flows[k] = f
            with self.m.lock:
                self.m.flows_total += 1; self.m.flows_active = len(self.flows)
        f.last = p.ts
        if p.src == f.client:
            f.pc += 1; f.bc += p.wirelen
        else:
            f.ps += 1; f.bs += p.wirelen
        if p.proto == D.TCP:
            fl = p.flags
            if fl & D.SYN and not fl & D.ACK:
                f.syn = True
            elif fl & D.SYN and fl & D.ACK:
                f.synack = True
            if fl & D.RST:
                f.rst = True
            if fl & D.FIN:
                f.fin = True
        if p.tls and p.tls.get("sni"):
            f.name = p.tls["sni"]; self.names.setdefault(f.server, f.name)
        elif p.http and p.http.get("kind") == "request" and p.http.get("host"):
            host = p.http["host"].split(":")[0]
            if not host.replace(".", "").isdigit():
                f.name = host; self.names.setdefault(f.server, host)
        return f

    def _expire(self, now):
        dead = [k for k, f in self.flows.items()
                if now - f.last > (30 if (f.fin or f.rst) else 120 if f.proto == D.TCP else 60)]
        for k in dead:
            f = self.flows.pop(k)
            for d in self.detectors:
                d.on_flow_end(f, self)
        with self.m.lock:
            self.m.flows_active = len(self.flows)

